### ISSUE TITLE
Initiation roadmap

### ISSUE THREAD

**Issue by danielrosehill** [danielrosehill/ImpactWeightedAccounts#1]
- [ ] Recreate data releases without password-protected worksheets
- [ ] Convert data releases to .odf
- [ ] Add post-analysis versions of data releases 
- [ ] Convert data releases to JSON
